### ISSUE TITLE
WARNING: ( homebridge-alexa) Dropped event message, message rate too high.

### ISSUE THREAD

**Issue by Pblondin123** [NorthernMan54/homebridge-alexa#458]
Hi, thanks for the plugin, much used at our home.   I recently added 4 motion sensors to HB (via envisalink) which are pretty active on events.   This caused in my view the dropped event message, so i used the allow devices list feature from the Alexa plugin.   Went from 80+ to 30+ devices discovered by the Alexa plugin, obviously without the motion sensors as i don't need to monitor them in Alexa.   My problem is that i still get the message rate too high message even with 30+ devices.    Is the objective of the allow list to filter on the traffic going out or am i misusing the feature perhaps ?   Thanks!

**Comment by NorthernMan54** [comment]
Give me a few days to look at the how the HomeKit event registration logic works with filtering.   My gut says that the device filtering is only applied to the Alexa discovery response, and not on the HomeKit event registration.  ( If a device is not registered for events, then events are not generated on change triggering the message)

**Comment by NorthernMan54** [comment]
Are you using routines trigger by Homebridge events ?  If not you can turn of routines in the config, and it will disable event registration.

**Comment by Pblondin123** [comment]
Hi, pretty much all my Alexa routines are triggered by HB events, so i will leave config on correct?  thnks

**Comment by NorthernMan54** [comment]
Correct, just checking for a quick workaround

**Comment by NorthernMan54** [comment]
@pwilms Any thoughts on this ?

**Comment by joaodforce** [comment]
I seem to be having the same issue. I have 6 cameras with motion sensing and and 2 contact sensors, however I only exposed one of the contact sensors (which im using as a doorbell) and my garage door, but it seems the plugin is sending updated from everything.

I'm using  v0.5.39.
Tell me if additional debugging information is needed.

<img width="1086" alt="image" src="https://user-images.githubusercontent.com/9410916/130373881-0fbe51d3-0611-4555-8cac-99f1a12f5b4a.png">

**Comment by NorthernMan54** [comment]
Just a quick update, I working thru updating the device filtering logic to also filter event registration.  Expect a pull request once I have completed the coding and testing.

**Comment by NorthernMan54** [comment]
Everyone,

I have released a beta that implements device list filtering for event registration.  If you can install the latest beta, and if you have implemented devicelist filters, it should now filter them from events.

**Comment by Pblondin123** [comment]
> Everyone,
> 
> I have released a beta that implements device list filtering for event registration. If you can install the latest beta, and if you have implemented devicelist filters, it should now filter them from events.

Hi!  good news, sorry am not sure how to download the beta i'll wait for techy colleagues to test but will provide feedback for sure after it will be in prod

**Comment by joaodforce** [comment]
Great news, im installing the beta, will do some tests and get back to you.
@Pblondin123 To install the beta, you go to homebridge ui plugins page, click the little wrench, and pick "install previous versions" and in the list the beta should appear

**Comment by Pblondin123** [comment]
> Great news, im installing the beta, will do some tests and get back to you.
> @Pblondin123 To install the beta, you go to homebridge ui plugins page, click the little wrench, and pick "install previous versions" and in the list the beta should appear

Thanks!  v0.5.49 installed and running on my HB.  36 devices in the list.   will monitor thanks

**Comment by Pblondin123** [comment]
> > Great news, im installing the beta, will do some tests and get back to you.
> > @Pblondin123 To install the beta, you go to homebridge ui plugins page, click the little wrench, and pick "install previous versions" and in the list the beta should appear
> 
> Thanks! v0.5.49 installed and running on my HB. 19/36 devices in the list. will monitor thanks

Hi again, just wanted to report that am still getting the Dropped event message, message rate too high message.  I have 4 live motion detectors (2 more than the other 2), not sure if this is helping your troubleshoot thanks.

**Comment by joaodforce** [comment]
Same here.

<img width="971" alt="image" src="https://user-images.githubusercontent.com/9410916/136109584-6cec9a0a-48bc-4c12-8dfb-237c83f41baa.png">

**Comment by NorthernMan54** [comment]
The beta should have enabled device filtering for event sources, this was not previously implemented in the plugin.  I made a minor tweak to the DEBUG logging, to include more details about what device's are event enabled.  You should be able to validate that the device filtering is working correctly by looking at the 'registerEvents' log message.  This will appear shortly after startup.

**Comment by NorthernMan54** [comment]
@joaodforce if you enable debug logging, it will log each event message so you can see some details around the devices sending messages.  Mind you the details you see are pretty cryptic, as they are the internal message format but may give some clue into the trigger.

**Comment by Pblondin123** [comment]
so far so good i believe (haven't seen the warning message in the log) will test some more
